//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_usagers
{
    using System;
    using System.Collections.Generic;
    
    public partial class enfants
    {
        public int ID { get; set; }
        public string num_dossier { get; set; }
        public string date_admission { get; set; }
        public string nom_enfant { get; set; }
        public string prenom_enfant { get; set; }
        public string service { get; set; }
        public string date_naissance { get; set; }
        public string lieu_naissance { get; set; }
    }
}
